# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [
          "17", # Old LTS
          "21" # Current LTS
        ]
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - if: matrix.java == '21'
        name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: Artifacts
          path: build/libs/*.jar
